import { Hotel } from "./types";

export const DEMO_HOTELS: Hotel[] = [
  {
    id: "demo-1",
    name: "Grand Palace Hotel",
    description: "A luxurious 5-star hotel in the heart of the city with world-class amenities and exceptional service.",
    category: "Luxury",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
    ],
    rating: 4.8,
    reviewCount: 1250,
    location: {
      address: "123 Main Street, Downtown",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Elevator/Lift", "Housekeeping", "Room Service", "Air Conditioning", "Free Wi-Fi", "Free Parking"],
      generalServices: ["Luggage Assistance", "Doctor on Call", "Multilingual Staff"],
      healthAndWellness: ["First-aid Services", "Gym", "Spa", "Swimming Pool"],
      transfers: ["Paid Airport Transfers", "Paid Shuttle Service"],
      roomAmenities: ["Mineral Water", "Hairdryer", "Air Conditioning", "Toiletries", "Work Desk"],
      foodAndDrinks: ["Restaurant", "Dining Area", "Barbeque"],
      safetyAndSecurity: ["CCTV", "Fire Extinguishers", "Security Alarms", "Security Guard"],
      entertainment: ["Entertainment", "Movie Room", "Music System"],
      commonArea: ["Lounge", "Balcony/Terrace", "Reception", "Garden"],
      businessCenter: ["Printer", "Conference Room", "Banquet", "Business Centre"],
      otherFacilities: ["Cloak Room", "Concierge"],
    },
    roomTypes: [
      {
        id: "room-1",
        name: "Deluxe Room - Queen Bed",
        size: "250 sq.ft (23 sq.mt)",
        view: "City View",
        bedType: "Queen Bed",
        bedCount: 1,
        bathrooms: 1,
        images: [],
        amenities: ["Daily Housekeeping", "Free Wi-Fi", "In-room Dining", "Room Service", "Bathroom", "Mineral Water"],
        plans: [
          {
            id: "plan-1",
            name: "Room With Free Cancellation",
            features: ["Free stay for the kid", "10% Discount On F&B Services"],
            originalPrice: 2500,
            discountedPrice: 1257,
            taxesAndFees: 171,
            freeCancellation: true,
          },
          {
            id: "plan-2",
            name: "Room with Breakfast",
            features: ["Free stay for the kid", "Complimentary Breakfast"],
            originalPrice: 3400,
            discountedPrice: 1709,
            taxesAndFees: 232,
            freeCancellation: true,
          },
        ],
      },
      {
        id: "room-2",
        name: "Executive Suite",
        size: "450 sq.ft (42 sq.mt)",
        view: "Pool View",
        bedType: "King Bed",
        bedCount: 1,
        bathrooms: 2,
        images: [],
        amenities: ["Daily Housekeeping", "Free Wi-Fi", "In-room Dining", "Room Service", "Bathroom", "Mineral Water", "Air Conditioning"],
        plans: [
          {
            id: "plan-3",
            name: "Suite With Free Cancellation",
            features: ["Free stay for the kid", "Complimentary Minibar"],
            originalPrice: 5500,
            discountedPrice: 3759,
            taxesAndFees: 512,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "demo-2",
    name: "Seaside Beach Resort",
    description: "Wake up to breathtaking ocean views at our beachfront resort with private beach access.",
    category: "Resort",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
    ],
    rating: 4.6,
    reviewCount: 890,
    location: {
      address: "Beach Road, Coastal Area",
      city: "Goa",
      state: "Goa",
      pincode: "403001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Housekeeping", "Room Service", "Air Conditioning", "Free Wi-Fi"],
      generalServices: ["Luggage Assistance", "Doctor on Call"],
      healthAndWellness: ["Spa", "Swimming Pool"],
      transfers: ["Paid Airport Transfers"],
      roomAmenities: ["Mineral Water", "Toiletries"],
      foodAndDrinks: ["Restaurant", "Barbeque"],
      safetyAndSecurity: ["CCTV", "Security Guard"],
      entertainment: ["Entertainment"],
      commonArea: ["Lounge", "Balcony/Terrace", "Garden"],
      businessCenter: [],
      otherFacilities: ["Concierge"],
    },
    roomTypes: [
      {
        id: "room-3",
        name: "Ocean View Cottage",
        size: "350 sq.ft",
        view: "Ocean View",
        bedType: "King Bed",
        bedCount: 1,
        bathrooms: 1,
        images: [],
        amenities: ["Daily Housekeeping", "Free Wi-Fi", "Balcony"],
        plans: [
          {
            id: "plan-4",
            name: "Beach Getaway Package",
            features: ["Complimentary Beach Umbrella", "Welcome Drink"],
            originalPrice: 8000,
            discountedPrice: 5999,
            taxesAndFees: 720,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "demo-3",
    name: "Mountain View Lodge",
    description: "Escape to the mountains with stunning views and cozy accommodation perfect for nature lovers.",
    category: "Boutique",
    images: [
      "https://images.unsplash.com/photo-1586611292717-f828b167408c?w=800",
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800",
    ],
    rating: 4.7,
    reviewCount: 456,
    location: {
      address: "Hill Station Road",
      city: "Shimla",
      state: "Himachal Pradesh",
      pincode: "171001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Housekeeping", "Room Service", "Free Wi-Fi", "Free Parking"],
      generalServices: ["Luggage Assistance"],
      healthAndWellness: ["First-aid Services"],
      transfers: [],
      roomAmenities: ["Mineral Water", "Heater", "Fireplace"],
      foodAndDrinks: ["Restaurant"],
      safetyAndSecurity: ["CCTV", "Fire Extinguishers"],
      entertainment: ["Music System"],
      commonArea: ["Lounge", "Balcony/Terrace", "Garden"],
      businessCenter: [],
      otherFacilities: [],
    },
    roomTypes: [
      {
        id: "room-4",
        name: "Mountain View Room",
        size: "280 sq.ft",
        view: "Mountain View",
        bedType: "Double Bed",
        bedCount: 1,
        bathrooms: 1,
        images: [],
        amenities: ["Heater", "Free Wi-Fi", "Mountain View"],
        plans: [
          {
            id: "plan-5",
            name: "Cozy Mountain Stay",
            features: ["Welcome Hot Chocolate", "Bonfire Access"],
            originalPrice: 4500,
            discountedPrice: 3299,
            taxesAndFees: 396,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "demo-4",
    name: "City Business Hotel",
    description: "Perfect for business travelers with modern amenities and excellent connectivity.",
    category: "Business Hotel",
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
    ],
    rating: 4.4,
    reviewCount: 780,
    location: {
      address: "Corporate Park, Sector 5",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Elevator/Lift", "Housekeeping", "Room Service", "Air Conditioning", "Free Wi-Fi"],
      generalServices: ["Luggage Assistance", "Multilingual Staff"],
      healthAndWellness: ["Gym"],
      transfers: ["Paid Airport Transfers"],
      roomAmenities: ["Mineral Water", "Work Desk", "Iron/Ironing Board"],
      foodAndDrinks: ["Restaurant"],
      safetyAndSecurity: ["CCTV", "Security Guard"],
      entertainment: [],
      commonArea: ["Reception"],
      businessCenter: ["Printer", "Conference Room", "Business Centre"],
      otherFacilities: [],
    },
    roomTypes: [
      {
        id: "room-5",
        name: "Business Standard Room",
        size: "220 sq.ft",
        view: "City View",
        bedType: "Queen Bed",
        bedCount: 1,
        bathrooms: 1,
        images: [],
        amenities: ["Work Desk", "Free Wi-Fi", "High-Speed Internet"],
        plans: [
          {
            id: "plan-6",
            name: "Corporate Rate",
            features: ["Express Check-in", "Late Checkout"],
            originalPrice: 3500,
            discountedPrice: 2499,
            taxesAndFees: 300,
            freeCancellation: false,
          },
        ],
      },
    ],
    createdAt: new Date("2024-04-05"),
  },
  {
    id: "demo-5",
    name: "Budget Inn Express",
    description: "Affordable and comfortable stay for budget-conscious travelers.",
    category: "Budget",
    images: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    ],
    rating: 4.0,
    reviewCount: 320,
    location: {
      address: "Near Railway Station",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Housekeeping", "Air Conditioning", "Free Wi-Fi"],
      generalServices: [],
      healthAndWellness: [],
      transfers: [],
      roomAmenities: ["Mineral Water"],
      foodAndDrinks: [],
      safetyAndSecurity: ["CCTV"],
      entertainment: [],
      commonArea: ["Reception"],
      businessCenter: [],
      otherFacilities: [],
    },
    roomTypes: [
      {
        id: "room-6",
        name: "Standard Room",
        size: "150 sq.ft",
        view: "Standard",
        bedType: "Double Bed",
        bedCount: 1,
        bathrooms: 1,
        images: [],
        amenities: ["Free Wi-Fi", "AC"],
        plans: [
          {
            id: "plan-7",
            name: "Basic Stay",
            features: ["No meals included"],
            originalPrice: 1200,
            discountedPrice: 899,
            taxesAndFees: 108,
            freeCancellation: false,
          },
        ],
      },
    ],
    createdAt: new Date("2024-05-12"),
  },
  {
    id: "demo-6",
    name: "Heritage Palace Hotel",
    description: "Experience royal hospitality in this restored heritage property with authentic decor.",
    category: "Heritage",
    images: [
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
    ],
    rating: 4.9,
    reviewCount: 560,
    location: {
      address: "Palace Road, Old City",
      city: "Jaipur",
      state: "Rajasthan",
      pincode: "302001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Housekeeping", "Room Service", "Air Conditioning", "Free Wi-Fi", "Free Parking"],
      generalServices: ["Luggage Assistance", "Doctor on Call", "Multilingual Staff"],
      healthAndWellness: ["Spa", "Swimming Pool"],
      transfers: ["Paid Airport Transfers"],
      roomAmenities: ["Mineral Water", "Toiletries"],
      foodAndDrinks: ["Restaurant", "Dining Area"],
      safetyAndSecurity: ["CCTV", "Security Guard"],
      entertainment: ["Entertainment"],
      commonArea: ["Lounge", "Garden"],
      businessCenter: ["Conference Room"],
      otherFacilities: ["Concierge"],
    },
    roomTypes: [
      {
        id: "room-7",
        name: "Royal Suite",
        size: "600 sq.ft",
        view: "Garden View",
        bedType: "King Bed",
        bedCount: 1,
        bathrooms: 2,
        images: [],
        amenities: ["Royal Decor", "Personal Butler", "Free Wi-Fi"],
        plans: [
          {
            id: "plan-8",
            name: "Royal Experience",
            features: ["Welcome Ceremony", "Heritage Tour", "Royal Breakfast"],
            originalPrice: 15000,
            discountedPrice: 11999,
            taxesAndFees: 1440,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-06-01"),
  },
  {
    id: "demo-7",
    name: "Riverside Retreat",
    description: "Peaceful riverside property perfect for relaxation and rejuvenation.",
    category: "Boutique",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
    ],
    rating: 4.5,
    reviewCount: 230,
    location: {
      address: "River Bank Road",
      city: "Rishikesh",
      state: "Uttarakhand",
      pincode: "249201",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Housekeeping", "Free Wi-Fi"],
      generalServices: ["Luggage Assistance"],
      healthAndWellness: ["Spa", "Yoga Studio"],
      transfers: [],
      roomAmenities: ["Mineral Water", "Balcony"],
      foodAndDrinks: ["Restaurant"],
      safetyAndSecurity: ["CCTV"],
      entertainment: [],
      commonArea: ["Lounge", "Balcony/Terrace", "Garden"],
      businessCenter: [],
      otherFacilities: [],
    },
    roomTypes: [
      {
        id: "room-8",
        name: "River View Cottage",
        size: "300 sq.ft",
        view: "River View",
        bedType: "Double Bed",
        bedCount: 1,
        bathrooms: 1,
        images: [],
        amenities: ["River View", "Private Balcony", "Free Wi-Fi"],
        plans: [
          {
            id: "plan-9",
            name: "Wellness Package",
            features: ["Morning Yoga Session", "Ayurvedic Breakfast"],
            originalPrice: 6000,
            discountedPrice: 4499,
            taxesAndFees: 540,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-07-15"),
  },
  {
    id: "demo-8",
    name: "The Premium Suites",
    description: "Upscale all-suite hotel with exceptional service and premium amenities.",
    category: "Premium",
    images: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
    ],
    rating: 4.7,
    reviewCount: 890,
    location: {
      address: "MG Road, Commercial District",
      city: "Delhi",
      state: "Delhi",
      pincode: "110001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Elevator/Lift", "Housekeeping", "Room Service", "Air Conditioning", "Free Wi-Fi", "Free Parking"],
      generalServices: ["Luggage Assistance", "Doctor on Call", "Multilingual Staff"],
      healthAndWellness: ["Gym", "Spa"],
      transfers: ["Paid Airport Transfers", "Paid Shuttle Service"],
      roomAmenities: ["Mineral Water", "Hairdryer", "Work Desk", "Toiletries"],
      foodAndDrinks: ["Restaurant", "Dining Area"],
      safetyAndSecurity: ["CCTV", "Security Guard"],
      entertainment: ["Entertainment"],
      commonArea: ["Lounge", "Reception"],
      businessCenter: ["Conference Room", "Business Centre"],
      otherFacilities: ["Concierge"],
    },
    roomTypes: [
      {
        id: "room-9",
        name: "Premium Suite",
        size: "500 sq.ft",
        view: "City View",
        bedType: "King Bed",
        bedCount: 1,
        bathrooms: 2,
        images: [],
        amenities: ["Living Area", "Work Desk", "Premium Toiletries"],
        plans: [
          {
            id: "plan-10",
            name: "Premium Stay",
            features: ["Complimentary Minibar", "Club Access", "Premium Breakfast"],
            originalPrice: 9000,
            discountedPrice: 6999,
            taxesAndFees: 840,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-08-20"),
  },
  {
    id: "demo-9",
    name: "Lakeside Paradise Resort",
    description: "Stunning lakeside resort offering water activities and serene natural beauty.",
    category: "Resort",
    images: [
      "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    ],
    rating: 4.6,
    reviewCount: 445,
    location: {
      address: "Lake Road",
      city: "Udaipur",
      state: "Rajasthan",
      pincode: "313001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Housekeeping", "Room Service", "Air Conditioning", "Free Wi-Fi"],
      generalServices: ["Luggage Assistance", "Doctor on Call"],
      healthAndWellness: ["Spa", "Swimming Pool"],
      transfers: ["Paid Airport Transfers"],
      roomAmenities: ["Mineral Water", "Toiletries", "Balcony"],
      foodAndDrinks: ["Restaurant", "Barbeque"],
      safetyAndSecurity: ["CCTV", "Security Guard"],
      entertainment: ["Entertainment"],
      commonArea: ["Lounge", "Balcony/Terrace", "Garden"],
      businessCenter: [],
      otherFacilities: ["Concierge"],
    },
    roomTypes: [
      {
        id: "room-10",
        name: "Lake View Villa",
        size: "550 sq.ft",
        view: "Lake View",
        bedType: "King Bed",
        bedCount: 1,
        bathrooms: 2,
        images: [],
        amenities: ["Private Balcony", "Lake View", "Jacuzzi"],
        plans: [
          {
            id: "plan-11",
            name: "Romantic Getaway",
            features: ["Candlelight Dinner", "Boat Ride", "Couples Spa"],
            originalPrice: 12000,
            discountedPrice: 8999,
            taxesAndFees: 1080,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-09-05"),
  },
  {
    id: "demo-10",
    name: "Standard Stay Inn",
    description: "Comfortable mid-range hotel with all essential amenities for a pleasant stay.",
    category: "Standard",
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800",
    ],
    rating: 4.2,
    reviewCount: 560,
    location: {
      address: "Main Market Road",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600001",
      country: "India",
    },
    amenities: {
      basicFacilities: ["Power Backup", "Housekeeping", "Room Service", "Air Conditioning", "Free Wi-Fi"],
      generalServices: ["Luggage Assistance"],
      healthAndWellness: [],
      transfers: [],
      roomAmenities: ["Mineral Water", "Toiletries"],
      foodAndDrinks: ["Restaurant"],
      safetyAndSecurity: ["CCTV"],
      entertainment: [],
      commonArea: ["Reception"],
      businessCenter: [],
      otherFacilities: [],
    },
    roomTypes: [
      {
        id: "room-11",
        name: "Standard Double Room",
        size: "200 sq.ft",
        view: "Standard",
        bedType: "Double Bed",
        bedCount: 1,
        bathrooms: 1,
        images: [],
        amenities: ["AC", "Free Wi-Fi", "TV"],
        plans: [
          {
            id: "plan-12",
            name: "Value Stay",
            features: ["Complimentary Breakfast"],
            originalPrice: 2200,
            discountedPrice: 1599,
            taxesAndFees: 192,
            freeCancellation: true,
          },
        ],
      },
    ],
    createdAt: new Date("2024-10-10"),
  },
];

// Standard Room Types that can be shared across hotels
export const DEMO_ROOM_TYPES = [
  {
    id: "std-rt-1",
    name: "Deluxe Room",
    size: "250 sq.ft (23 sq.mt)",
    view: "City View",
    bedType: "Queen Bed",
    bedCount: 1,
    bathrooms: 1,
    images: [],
    amenities: ["Daily Housekeeping", "Free Wi-Fi", "In-room Dining", "Room Service", "Bathroom", "Mineral Water"],
    plans: [
      {
        id: "std-plan-1",
        name: "Room Only",
        features: ["No meals included"],
        originalPrice: 3500,
        discountedPrice: 2499,
        taxesAndFees: 300,
        freeCancellation: true,
      },
      {
        id: "std-plan-2",
        name: "Room with Breakfast",
        features: ["Complimentary Breakfast", "Free stay for kids"],
        originalPrice: 4500,
        discountedPrice: 3199,
        taxesAndFees: 384,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "std-rt-2",
    name: "Executive Suite",
    size: "450 sq.ft (42 sq.mt)",
    view: "Pool View",
    bedType: "King Bed",
    bedCount: 1,
    bathrooms: 2,
    images: [],
    amenities: ["Daily Housekeeping", "Free Wi-Fi", "In-room Dining", "Room Service", "Bathroom", "Mineral Water", "Air Conditioning", "Work Desk"],
    plans: [
      {
        id: "std-plan-3",
        name: "Suite with Free Cancellation",
        features: ["Complimentary Minibar", "Late Checkout"],
        originalPrice: 7500,
        discountedPrice: 5499,
        taxesAndFees: 660,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "std-rt-3",
    name: "Family Room",
    size: "380 sq.ft (35 sq.mt)",
    view: "Garden View",
    bedType: "Twin Beds",
    bedCount: 2,
    bathrooms: 1,
    images: [],
    amenities: ["Daily Housekeeping", "Free Wi-Fi", "Room Service", "Bathroom", "Mineral Water", "Air Conditioning", "Kids Play Area"],
    plans: [
      {
        id: "std-plan-4",
        name: "Family Package",
        features: ["Kids eat free", "Board games", "Extra bed available"],
        originalPrice: 5500,
        discountedPrice: 3999,
        taxesAndFees: 480,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "std-rt-4",
    name: "Premium Suite",
    size: "600 sq.ft (56 sq.mt)",
    view: "Ocean View",
    bedType: "King Bed",
    bedCount: 1,
    bathrooms: 2,
    images: [],
    amenities: ["Daily Housekeeping", "Free Wi-Fi", "In-room Dining", "24-hour Room Service", "Bathroom", "Mineral Water", "Air Conditioning", "Work Desk", "Living Room"],
    plans: [
      {
        id: "std-plan-5",
        name: "Premium Experience",
        features: ["Club Access", "Premium Breakfast", "Airport Transfer"],
        originalPrice: 12000,
        discountedPrice: 8999,
        taxesAndFees: 1080,
        freeCancellation: true,
      },
    ],
  },
  {
    id: "std-rt-5",
    name: "Studio Room",
    size: "200 sq.ft (19 sq.mt)",
    view: "Standard",
    bedType: "Double Bed",
    bedCount: 1,
    bathrooms: 1,
    images: [],
    amenities: ["Free Wi-Fi", "Room Service", "Bathroom", "Air Conditioning"],
    plans: [
      {
        id: "std-plan-6",
        name: "Budget Stay",
        features: ["No meals included"],
        originalPrice: 2000,
        discountedPrice: 1299,
        taxesAndFees: 156,
        freeCancellation: false,
      },
    ],
  },
  {
    id: "std-rt-6",
    name: "Presidential Suite",
    size: "1000 sq.ft (93 sq.mt)",
    view: "Panoramic View",
    bedType: "King Bed",
    bedCount: 1,
    bathrooms: 3,
    images: [],
    amenities: ["Daily Housekeeping", "Free Wi-Fi", "In-room Dining", "24-hour Room Service", "Bathroom", "Mineral Water", "Air Conditioning", "Work Desk", "Living Room", "Private Balcony", "Personal Butler"],
    plans: [
      {
        id: "std-plan-7",
        name: "Royal Treatment",
        features: ["Personal Butler", "Private Check-in", "Complimentary Spa", "Limousine Transfer"],
        originalPrice: 35000,
        discountedPrice: 25999,
        taxesAndFees: 3120,
        freeCancellation: true,
      },
    ],
  },
];
